import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body className={inter.className}>
        {children}
        <Script id="simiriki-chat-config" strategy="afterInteractive">
          {`
            window.ChatGPTConfig = {
              token: "<INSERT_OPENAI_CHAT_WIDGET_TOKEN_HERE>",
              containerId: "simirikiChatWidget",
              welcomeMessage: "Hola 👋 ¿En qué puedo ayudarte con la automatización de tu negocio?",
              theme: "light"
            };
          `}
        </Script>
        <Script
          src="https://cdn.simiriki.com/widgets/chatgpt.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
